# Jekyll configuration
name: S. R. G. Balestra's site
description: "Researcher in all things "
keywords: "Hagen Wierstorf, researcher, publications, nanoporous materials, physic, complex systems"
# url is currently only used only for the RSS feed in feed.xml
url: http://salrodgom.github.io

# baseurl will often be '', but for a project page on gh-pages, it needs to
# be the project name.
# *** IMPORTANT: If your local "jekyll serve" throws errors change this to '' or
#     run it like so: jekyll serve --baseurl=''
baseurl: null

# This can be '' to hide the Github nav button
github: ''
# Set this to your UA-# value, or '' to disable the block completely
gaaccount: ''

# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: ''
comments: true
# Author settings
author:
  name     : "Salvador Rodríguez-Gómez"
  job      : "Pre-Doc"
  bio      : "Researcher in all things"
  thumb    : /images/senegal_cut.jpg
  email    : salrodgom@upo.es
  url      : http://salrodgom.github.io
  github   : http://github.com/salrodgom
  twitter  : http://twitter.com/mcplatano

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
navbar:
  - slug : test
    title : Test

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
